version: "3"

services:
  database:
    image: postgres:12.2-alpine
    container_name: "user-manager-database"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "user-manager"
    volumes:
      - database-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  cache:
    image: redis:6.0.5-alpine
    container_name: "user-manager-cache"
    volumes:
      - cache-redis:/data
    ports:
      - "6379:6379"

  broker:
    image: rabbitmq:3.8.3-alpine
    container_name: "user-manager-broker"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "5672:5672"

volumes:
  database-postgres:
  cache-redis:
