"""Add user roles column

Revision ID: 549e0d1ac7d0
Revises: 8d202d5ddbde
Create Date: 2020-11-01 00:52:10.246201

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "549e0d1ac7d0"
down_revision = "8d202d5ddbde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("roles", sa.ARRAY(sa.Text(), dimensions=1), nullable=True)
    )
    op.execute("UPDATE users SET roles = ARRAY[]::TEXT[] WHERE roles IS NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
