"""add user email column

Revision ID: 8d202d5ddbde
Revises: b4b3ec3be937
Create Date: 2020-06-14 19:33:59.389126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d202d5ddbde"
down_revision = "b4b3ec3be937"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.Text(), nullable=False))
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
